### ISSUE TITLE
It's fully broken now, thank you :-D

### ISSUE THREAD

**Issue by Vitashakti** [JocysCom/VsAiCompanion#15]
It keeps saying "Please Provide the API Key" even though the user has entered the API Key. It takes you back to the setting to provide the API key which you already have.

See the attached photo: 1. API Key is provided. 2. Message that is asking for API Key. 3. Blue arrow on the right: the button is always disabled. 4. The blue arrow on the left: the Drop Down is always empty.

![image](https://github.com/user-attachments/assets/9985515e-9750-4a57-a85d-d533fc1952e6)

**Comment by EJocys** [comment]
Hi @Vitashakti ,

Thanks for reporting the issue. I've tested connection on the app to Azure but couldn't replicate the problem. I've updated the code to provide a clearer error message, which will be included in the next app update.

Regarding the "blue arrows": the Drop Down and Refresh buttons are only enabled when the "Options \ Main \ Enable Microsoft Account" option is enabled and the user is signed in. If you're accessing Microsoft Azure the AI service with an API key, you don't need to use Microsoft account.

Every time you restart the application, it attempts to clean up and fix AI service and model configurations. You can try restarting the application to see if it helps.

If you're using the Microsoft Azure OpenAI service, make sure the correct service is selected. It's easy to mix up "OpenAI" and "Azure OpenAI" services.

![image](https://github.com/user-attachments/assets/38a5e3d4-1765-4807-ac16-028a5abe37e1)

I'll try experimenting more to see if I can replicate the issue.

Kind regards,
Evaldas Jocys

**Comment by EJocys** [comment]
If you're asking the AI to analyse images or screenshots, it might be using another AI model specified in the `® System - Video` template. Go to [Templates] \ `® System - Video` template and select an AI service and AI model capable of image processing, probably "Azure OpenAI" service if you're not using "OpenAI", and the "GPT-4o" model.

![image](https://github.com/user-attachments/assets/1d0aa27d-b084-412c-99fb-297d6ecb6a9d)

**Comment by Vitashakti** [comment]
Hi Evaldas, thanks for clarification. The problem was my confusion over azure open ai and open ai. In a sense the API key that I provided wasn't right for Azure so it told me it was not provided. that's fine.
Now, can you please tell me where I can find detailed logs of the system? I'm getting a 403 error and want to see exactly on which request to which URL I got it.

**Comment by EJocys** [comment]
Originally, there's an option "[ ] Log HTTP Messages" that logs all traffic into this folder:
C:\Users\%USERNAME%\AppData\Roaming\Jocys.com\VS AI Companion\Logs
![image](https://github.com/user-attachments/assets/02abf92c-8778-4e57-87ed-d84866cfa9f8)

Unfortunately, it’s not working as expected. I’ll try to fix it in the next release.
Also, I found and fixed a bug where it would use `https://api.openai.com/v1` as the address for the OpenAPI service even if you specified another URL.

You can also enable "[x] Show Errors Panel:
![image](https://github.com/user-attachments/assets/04cb17cd-14eb-43e0-b0c4-09026b703be8)

**Comment by EJocys** [comment]
Closing. Updated the client and made a bunch of updates.
