### ISSUE TITLE
Having trouble with text streaming

### ISSUE THREAD

**Issue by grandoth** [JocysCom/VsAiCompanion#17]
I am getting back to experimenting with the VS AI Companion and to try to use it more in everyday tasks, I was trying to get text streaming to work. I can successfully get prompt responses, but sometimes it takes a while for longer text, and streaming would be nice.

I went through options and ensured my ollama AI service is set to "Response Streaming". I tried various combinations of "Features are known" and "Streaming". However, when I select another model and come back to the model I just changed checkboxes for, the "Streaming" checkbox becomes unchecked.

Full disclosure: 
I am using ollama locally using its version of the OpenAI API and for testing, I am using the llama 3.1 model.

I suspect I am just not understanding something. I appreciate any guidance you can provide.

**Comment by grandoth** [comment]
Don't spend any time on this yet. I think I may have figured it out. Debugging the application I see that my connection is not secure (http). I will attempt to resolve that and see if that fixes it.

**Comment by grandoth** [comment]
It's not clear to me if it just needs HTTPS. It seems like it also might need actual credentials, api key or otherwise. Being a local ollama server, I have no need to set up any of that. How difficult would it be to implement streaming over HTTP?

**Comment by EJocys** [comment]
@grandoth Thanks for reporting the issue. You're right, there should be an option to turn off HTTPS on local connection. I'll check again to see if streaming can be done over HTTP using the OpenAI client.

P.S.: I probably need to add more help files and instructions in the app, as it can be tricky to find the right configuration. For example, the Google Gemini API (compatible with OpenAI) also has issues with streaming, so I had to turn streaming off in the settings.

**Comment by EJocys** [comment]
@grandoth Fixed an issue with HTTP in the new release. It now uses the Microsoft OpenAI client for HTTP as well. Tested with LM Studio on `http://localhost:1234/v1/`.

2024-12-01 v1.16.7

- Fix: Copied chat could not be pasted as plain text.
- Fix: Database function call crash with SQLite.
- **Fix: Connection issue with the `http` schema for the local API (such as LM Studio).**
- New: Added support for OpenAI Text-to-Speech models.
- New: Added support for OpenAI Speech-to-Text models.
- New: Added `Open`, `Open With...`, `Edit`, and `Browse` buttons for Image and Audio attachments.
- Update: Chat has been updated to use the Microsoft Edge WebView2 control.

**Comment by grandoth** [comment]
Seems to work. A few comments/questions:
- In order to not get the following error, I needed to put in a dummy API key (e.g. "na"):
System.ArgumentException: Value cannot be an empty string.
Parameter name: key
   at System.ClientModel.Internal.Argument.AssertNotNullOrEmpty(String value, String name)
   at System.ClientModel.ApiKeyCredential.Update(String key)
   at JocysCom.VS.AiCompanion.Engine.Companions.ChatGPT.Client.<GetAiClient>d__41.MoveNext() in D:\Projects\Jocys.com GitHub\VsAiCompanion\Engine\Companions\ChatGPT\Client.cs:line 347
- Enabling streaming still provides responses, but the text doesn't update live in the UI as it is streamed. It shows up as a block at once. Maybe I was misunderstanding and made a bad assumption. Is the streaming option intended to update the UI live as the text comes in or just support the text if it comes in that way? I was sure to set "Response Streaming" in the AI Services and "Streaming" (which now sticks) in the AI Models settings.

**Comment by EJocys** [comment]
@grandoth "Is the streaming option intended to update the UI live as the text comes in"

Yes, the original plan was to update the UI live as the text comes in, but due to a lack of time, I never finished implementing it. Additionally, while streaming is a nice feature, I don't see how it could be useful in the future because good answers must go through multiple refactoring's and reviews, and reviewing sometimes requires reading from the end. This means that a perfect reply can't be streamed but should be returned as a whole, prepared product, because the AI must "know" what the ending will be before starting to the reply. Similar to humans, speaking on the go usually results in lower quality than delivering a fully prepared speech. :)

**Comment by grandoth** [comment]
Understand. For me personally, I can see some value. When you're working locally responses can take a long time especially when it is spitting out 2 pages of code. Even if the text was going through multiple transforms or post processing, I would find value in seeing it come through piecemeal even if changed later. I can determine if it hallucinated within a few seconds instead of waiting a minute just to see the response was garbage. Hallucinations and garbage responses are much more likely when working with smaller/lower fidelity models which are often the case when running locally.

**Comment by EJocys** [comment]
Updated and fixed streaming to the chat. Tested it with OpenAI GPT models and LM Studio hosting the `Meta-Llama-3.1-8B-Instruct-GGUF` model.

2024-12-15 v1.16.17

- Fix: Chat window not always staying scrolled to the bottom.
- New: App instance number indicator on the tray icon.
**- Update: Enable streaming of content directly from the server to the chat window.**
- Update: Improved several templates.

**Comment by grandoth** [comment]
Works well. Thanks so much!
