### ISSUE TITLE
Method not found error

### ISSUE THREAD

**Issue by candymachineater** [JocysCom/VsAiCompanion#9]
Open AI API key is set up.

keep getting error :

Method not found: 'System.Collections.Generic.IAsyncEnumerable1<!!0> System.Linq.AsyncEnumerable.AsAsyncEnumerable(System.Collections.Generic.IAsyncEnumerable1<!!0>)'.

**Comment by EJocys** [comment]
Hi @candymachineater,

Thanks for reporting the issue. One of the confirmed successful solutions is:

To make sure that you have the latest Microsoft .NET 8.0: https://dotnet.microsoft.com/download/dotnet

If you're using VS Companion as a Visual Studio extension, make sure your Visual Studio 2022 is updated to at least version 17.9. You can update Visual Studio by using the "Visual Studio Installer".

Please let me know if that doesn't resolve the issue. I'll add this advice to the next version of the VS AI Companion extension.

Kind Regards,
Evaldas Jocys
